services:
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  catalog.api-1:
    image: catalog.api-1
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  catalog.api-2:
    image: catalog.api-2
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

